FROM rockerextra/shiny-async-dev:3.4

RUN http_proxy=http://10.74.1.25:8080 apt-get update && \
    http_proxy=http://10.74.1.25:8080 apt-get install -y libssl-dev wget curl nano

RUN wget -e use_proxy=yes -e https_proxy=http://10.74.1.25:8080 https://www.rforge.net/src/contrib/Rserve_1.8-5.tar.gz \
    && /usr/local/bin/R CMD INSTALL Rserve_1.8-5.tar.gz

COPY ./api /home/rstudio/api
COPY ./jscript /home/rstudio/jscript
COPY ./shiny /srv/shiny-server/shiny

RUN mkdir -p /etc/services.d/rserve \
    && echo '#!/usr/bin/with-contenv bash \
        \n /usr/local/bin/R CMD Rserve --slave --RS-conf /home/rstudio/api/rserve.conf --RS-source /home/rstudio/api/rserve-src.R' \
        > /etc/services.d/rserve/run

RUN mkdir -p /etc/services.d/jscript \
    && echo '#!/usr/bin/with-contenv bash \
        \n python /home/rstudio/jscript/serve.py -d /home/rstudio/jscript -p 7000' \
        > /etc/services.d/jscript/run

EXPOSE 8000
EXPOSE 7000

CMD ["/init"]